export const Links = [
  {
    path: '/books/all',
    test: 'navigation-showcase',
    burger: 'burger-showcase',
    name: 'Витрина книг',
    seconds: [
      { name: 'Все книги', path: 'all', burger: 'burger-books', test: 'navigation-books' },
      { name: 'Бизнес-книги', quantity: 14, burger: '', test: '', path: 'business' },
      { name: 'Детективы', quantity: 8, burger: '', test: '', path: 'detectives' },
      { name: 'Детские книги', quantity: 14, burger: '', test: '', path: 'baby' },
      { name: 'Зарубежная литература', quantity: 2, burger: '', test: '', path: 'foreign' },
      { name: 'История', quantity: 5, burger: '', test: '', path: 'history' },
      { name: 'Классическая литература', quantity: 12, burger: '', test: '', path: 'classic' },
      { name: 'Книги по психологии', quantity: 11, burger: '', test: '', path: 'psychology' },
      { name: 'Компьютерная литература', quantity: 54, burger: '', test: '', path: 'computer' },
      { name: 'Культура и искусство', quantity: 5, burger: '', test: '', path: 'culture' },
      { name: 'Наука и образование', quantity: 2, burger: '', test: '', path: 'science' },
      { name: 'Публицистическая литература', quantity: 0, burger: '', test: '', path: 'journalistic' },
      { name: 'Справочники', quantity: 10, burger: '', test: '', path: 'reference' },
      { name: 'Фантастика', quantity: 12, burger: '', test: '', path: 'fantasy' },
      { name: 'Юмористическая литература', quantity: 10, burger: '', test: '', path: 'humorous' },
    ],
  },
  { path: '/rules', test: 'navigation-terms', burger: 'burger-terms', name: 'Правила пользования' },
  { path: '/treaty', test: 'navigation-contract', burger: 'burger-contract', name: 'Договор оферты' },
  { path: '/profile', test: '', burger: '', name: 'Профиль' },
  { path: '/exit', test: '', burger: '', name: 'Выход' },
];
